# Generated by Django 5.1.2 on 2024-11-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_alter_products_price_alter_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='numReview',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
